# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  assertions:
    - resource: Microsoft.Windows.Developer/OsVersion
      directives:
        description: Verify min OS version requirement
        allowPrerelease: true
      settings:
        MinVersion: '10.0.22000'
  resources:
    - resource: Microsoft.Windows.Developer/DeveloperMode
      directives:
        description: Enable Developer Mode
        allowPrerelease: true
      settings:
        Ensure: Present
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: vsPackage
      directives:
        description: Install Visual Studio 2022 Professional
        allowPrerelease: true
      settings:
        id: Microsoft.VisualStudio.2022.Professional
        source: winget
    - resource: Microsoft.VisualStudio.DSC/VSComponents
      dependsOn:
        - vsPackage
      directives:
        description: Install required VS workloads from vsconfig file
        allowPrerelease: true
      settings:
        productId: Microsoft.VisualStudio.Product.Professional
        channelId: VisualStudio.17.Release
        vsConfigFile: '${WinGetConfigRoot}\..\.vsconfig\VS2022\.vsconfig'
        includeRecommended: true
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Git
      directives:
        description: Install Git
        allowPrerelease: true
      settings:
        id: Git.Git
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: VSCode
      directives:
        description: Install Visual Studio Code
        allowPrerelease: true
      settings:
        id: Microsoft.VisualStudioCode
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: PowerShell7
      directives:
        description: Install PowerShell 7
        allowPrerelease: true
      settings:
        id: Microsoft.PowerShell
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Docker Desktop
      directives:
        description: Install Docker Desktop
        allowPrerelease: true
      settings:
        id: Docker.DockerDesktop
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Azure CLI
      directives:
        description: Install Azure CLI
        allowPrerelease: true
      settings:
        id: Microsoft.AzureCLI
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: GitHub CLI
      directives:
        description: Install GitHub CLI
        allowPrerelease: true
      settings:
        id: GitHub.cli
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      dependsOn:
        - PowerShell7
      id: Oh My Posh
      directives:
        description: Install Oh My Posh
        allowPrerelease: true
      settings:
        id: JanDeDobbeleer.OhMyPosh
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: NVM
      directives:
        description: Install NVM for Windows
        allowPrerelease: true
      settings:
        id: CoreyButler.NVMforWindows
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: OpenLens
      directives:
        description: Install OpenLens
        allowPrerelease: true
      settings:
        id: MuhammedKalkan.OpenLens
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: PowerToys
      directives:
        description: Install PowerToys
        allowPrerelease: true
      settings:
        id: Microsoft.PowerToys
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: BeyondCompare
      directives:
        description: Install Beyond Compare
        allowPrerelease: true
      settings:
        id: ScooterSoftware.BeyondCompare4
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Notepad++
      directives:
        description: Install Notepad++
        allowPrerelease: true
      settings:
        id: Notepad++.Notepad++
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Chrome
      directives:
        description: Install Chrome
        allowPrerelease: true
      settings:
        id: Google.Chrome
        source: winget

  configurationVersion: 0.2.0